name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PRETTIER_TOKEN}}

      - name: Prettier
        run: |
          git fetch --all
          git reset --hard origin/master
          npm i -g prettier
          prettier --use-tabs	true --quote-props consistent --trailing-comma es5 --write .

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git pull -X ours
          git add .
          git commit --amend --no-edit
          git push -f
