on:
  issues:
    types: [ assigned ]
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: chatops
          branchName: '${issue.number}-${issue.title}'
          autoCloseIssue: true
          openDraftPR: true
          copyIssueDescriptionToPR: true
          copyIssueAssigneeToPR: true
          copyIssueLabelsToPR: true
          commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
          experimental:
            branchNameArgument: true
