on:
  pull_request_review:
    types: [submitted]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: BrianMitchL/pr-chatter-action@v1
      with:
        # required
        TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
        # optional
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # optional
        approved-gif-keywords: 'amazing, approve, awesome, great work, good job, hooray, incredible, joy, looks good, nice, perfect, thumbs up, wonderful'
        # optional
        changes-requested-gif-keywords: 'try again, review, at least you tried, so close, dumpster fire, terrible, awful, disgusting, sad'
